language: cpp

sudo: required
script:
  - gcc --version
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5

dist: trusty

compiler:
  - clang
  - gcc

script: sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc && ./autogen.sh && ./configure --without-liquid --without-sndfile && make
